package cmd

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"github.com/nextlevelbuilder/goclaw/internal/config"
)

func onboardGenerateToken(bytes int) string {
	b := make([]byte, bytes)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func onboardWriteEnvFile(path string, cfg *config.Config, primaryKey, primaryEnvKey string, traceVerbose bool) {
	var lines []string
	lines = append(lines, "# GoClaw — auto-generated by onboard wizard")
	lines = append(lines, "# Keep this file secret! Add to .gitignore.")
	lines = append(lines, "")

	if primaryEnvKey != "" && primaryKey != "" {
		lines = append(lines, fmt.Sprintf("export %s=%s", primaryEnvKey, primaryKey))
	}

	// Claude CLI config (no API key, just path/model)
	if cfg.Providers.ClaudeCLI.CLIPath != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_CLAUDE_CLI_PATH=%s", cfg.Providers.ClaudeCLI.CLIPath))
		if cfg.Providers.ClaudeCLI.Model != "" {
			lines = append(lines, fmt.Sprintf("export GOCLAW_CLAUDE_CLI_MODEL=%s", cfg.Providers.ClaudeCLI.Model))
		}
	}

	// Add other configured provider keys (skip if same as primary)
	addIfSet := func(envKey, value string) {
		if value != "" && (primaryEnvKey == "" || envKey != primaryEnvKey) {
			lines = append(lines, fmt.Sprintf("export %s=%s", envKey, value))
		}
	}
	addIfSet("GOCLAW_ANTHROPIC_API_KEY", cfg.Providers.Anthropic.APIKey)
	addIfSet("GOCLAW_OPENAI_API_KEY", cfg.Providers.OpenAI.APIKey)
	addIfSet("GOCLAW_OPENROUTER_API_KEY", cfg.Providers.OpenRouter.APIKey)
	addIfSet("GOCLAW_GROQ_API_KEY", cfg.Providers.Groq.APIKey)
	addIfSet("GOCLAW_DEEPSEEK_API_KEY", cfg.Providers.DeepSeek.APIKey)
	addIfSet("GOCLAW_GEMINI_API_KEY", cfg.Providers.Gemini.APIKey)
	addIfSet("GOCLAW_MISTRAL_API_KEY", cfg.Providers.Mistral.APIKey)
	addIfSet("GOCLAW_XAI_API_KEY", cfg.Providers.XAI.APIKey)
	addIfSet("GOCLAW_MINIMAX_API_KEY", cfg.Providers.MiniMax.APIKey)
	addIfSet("GOCLAW_COHERE_API_KEY", cfg.Providers.Cohere.APIKey)
	addIfSet("GOCLAW_PERPLEXITY_API_KEY", cfg.Providers.Perplexity.APIKey)

	if cfg.Gateway.Token != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_GATEWAY_TOKEN=%s", cfg.Gateway.Token))
	}

	if cfg.Channels.Telegram.Enabled && cfg.Channels.Telegram.Token != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_TELEGRAM_TOKEN=%s", cfg.Channels.Telegram.Token))
	}
	if cfg.Channels.Zalo.Enabled && cfg.Channels.Zalo.Token != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_ZALO_TOKEN=%s", cfg.Channels.Zalo.Token))
	}
	if cfg.Channels.Feishu.Enabled && cfg.Channels.Feishu.AppSecret != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_FEISHU_APP_ID=%s", cfg.Channels.Feishu.AppID))
		lines = append(lines, fmt.Sprintf("export GOCLAW_FEISHU_APP_SECRET=%s", cfg.Channels.Feishu.AppSecret))
	}

	// Database
	if cfg.Database.PostgresDSN != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_POSTGRES_DSN=%s", cfg.Database.PostgresDSN))
	}

	// Encryption key for API keys in DB
	if encKey := os.Getenv("GOCLAW_ENCRYPTION_KEY"); encKey != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_ENCRYPTION_KEY=%s", encKey))
	}

	// TTS secrets
	if cfg.Tts.OpenAI.APIKey != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_TTS_OPENAI_API_KEY=%s", cfg.Tts.OpenAI.APIKey))
	}
	if cfg.Tts.ElevenLabs.APIKey != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_TTS_ELEVENLABS_API_KEY=%s", cfg.Tts.ElevenLabs.APIKey))
	}
	if cfg.Tts.MiniMax.APIKey != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_TTS_MINIMAX_API_KEY=%s", cfg.Tts.MiniMax.APIKey))
	}
	if cfg.Tts.MiniMax.GroupID != "" {
		lines = append(lines, fmt.Sprintf("export GOCLAW_TTS_MINIMAX_GROUP_ID=%s", cfg.Tts.MiniMax.GroupID))
	}

	// Verbose tracing
	if traceVerbose {
		lines = append(lines, "export GOCLAW_TRACE_VERBOSE=1")
	}

	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	_ = os.WriteFile(path, []byte(content), 0600)
}
