/**
 * Linear spectrogram DSP for the browser voice-clone pipeline.
 *
 * Pure, framework-free functions that mirror OpenVoice v2's
 * `spectrogram_torch` (openvoice/mel_processing.py) sample-for-sample:
 *
 *   1. reflect-pad the signal by (n_fft - hop) / 2 on both sides
 *   2. STFT with a periodic Hann window, center=False, normalized=False
 *   3. magnitude = sqrt(re² + im² + 1e-6)
 *
 * NOTE: the actual OpenVoice v2 converter/speaker-encoder inputs are the
 * LINEAR spectrogram (n_fft/2+1 = 513 frequency bins) — there is no mel
 * projection and no log in the voice-conversion path. Validated against
 * torch goldens generated by `contrib/voiceclone/export_onnx.py`
 * (see `spectrogram.test.ts`).
 */

import type { SpectrogramParams } from "./types";
import type { F32 } from "./audio";

/** Periodic Hann window (torch.hann_window default, periodic=true). */
export function hannWindow(size: number): Float32Array {
  const w = new Float32Array(size);
  for (let i = 0; i < size; i++) {
    w[i] = 0.5 - 0.5 * Math.cos((2 * Math.PI * i) / size);
  }
  return w;
}

/**
 * Reflect-pads `samples` by `pad` on both sides (torch F.pad reflect, which
 * excludes the edge sample: index -1 → 1, index n → n-2). Requires
 * `pad <= n - 1`, same as torch; shorter inputs are clamped defensively.
 */
export function reflectPad(samples: Float32Array, pad: number): Float32Array {
  if (pad <= 0) return samples.slice();
  const n = samples.length;
  const out = new Float32Array(n + pad * 2);
  const p = Math.min(pad, Math.max(0, n - 1));
  for (let i = 0; i < p; i++) {
    out[i] = samples[p - i] ?? 0;
    out[p + n + i] = samples[n - 2 - i] ?? 0;
  }
  out.set(samples, pad);
  return out;
}

/**
 * Iterative radix-2 in-place FFT. `re`/`im` must have length `n` = power of
 * two. Twiddle tables and bit-reversal are cached per size.
 */
const twiddleCache = new Map<number, { cos: Float32Array; sin: Float32Array; rev: Uint32Array }>();

function twiddles(n: number): { cos: Float32Array; sin: Float32Array; rev: Uint32Array } {
  const cached = twiddleCache.get(n);
  if (cached) return cached;
  const half = n >> 1;
  const cos = new Float32Array(half);
  const sin = new Float32Array(half);
  for (let i = 0; i < half; i++) {
    const ang = (-2 * Math.PI * i) / n;
    cos[i] = Math.cos(ang);
    sin[i] = Math.sin(ang);
  }
  const bits = Math.round(Math.log2(n));
  const rev = new Uint32Array(n);
  for (let i = 0; i < n; i++) {
    let r = 0;
    for (let b = 0; b < bits; b++) {
      r = (r << 1) | ((i >>> b) & 1);
    }
    rev[i] = r;
  }
  const t = { cos, sin, rev };
  twiddleCache.set(n, t);
  return t;
}

export function fftInPlace(re: Float32Array, im: Float32Array): void {
  const n = re.length;
  if (n <= 1 || (n & (n - 1)) !== 0) throw new Error(`fft: length ${n} must be a power of two`);
  const { cos, sin, rev } = twiddles(n);
  for (let i = 0; i < n; i++) {
    const j = rev[i] ?? 0;
    if (j > i) {
      let t = re[i] ?? 0;
      re[i] = re[j] ?? 0;
      re[j] = t;
      t = im[i] ?? 0;
      im[i] = im[j] ?? 0;
      im[j] = t;
    }
  }
  for (let size = 2; size <= n; size <<= 1) {
    const half = size >> 1;
    const step = n / size;
    for (let start = 0; start < n; start += size) {
      for (let k = 0; k < half; k++) {
        const tw = k * step;
        const wr = cos[tw] ?? 0;
        const wi = sin[tw] ?? 0;
        const i0 = start + k;
        const i1 = i0 + half;
        const re0 = re[i0] ?? 0;
        const im0 = im[i0] ?? 0;
        const re1 = re[i1] ?? 0;
        const im1 = im[i1] ?? 0;
        const xr = re1 * wr - im1 * wi;
        const xi = re1 * wi + im1 * wr;
        re[i1] = re0 - xr;
        im[i1] = im0 - xi;
        re[i0] = re0 + xr;
        im[i0] = im0 + xi;
      }
    }
  }
}

/**
 * Linear spectrogram, exactly `spectrogram_torch(y, n_fft, sr, hop, win,
 * center=False)`. Output layout is channel-major `[freq][time]`
 * (numBins × numFrames), ready to feed the ONNX graph (1, numBins, T).
 * Returns null for inputs too short to produce a single frame.
 */
export function linearSpectrogram(samples: Float32Array, p: SpectrogramParams): F32 | null {
  const pad = (p.n_fft - p.hop_length) / 2;
  if (!Number.isInteger(pad)) throw new Error(`spectrogram: (n_fft-hop)/2 must be integral, got ${pad}`);
  const window = hannWindow(p.win_length);
  const padded = reflectPad(samples, pad);
  const bins = p.n_fft / 2 + 1;
  const frames = spectrogramFrameCount(samples.length, p);
  if (frames <= 0) return null;
  const out = new Float32Array(bins * frames);
  const re = new Float32Array(p.n_fft);
  const im = new Float32Array(p.n_fft);
  for (let f = 0; f < frames; f++) {
    const off = f * p.hop_length;
    for (let i = 0; i < p.n_fft; i++) {
      re[i] = (padded[off + i] ?? 0) * (window[i] ?? 0);
      im[i] = 0;
    }
    fftInPlace(re, im);
    for (let b = 0; b < bins; b++) {
      const r = re[b] ?? 0;
      const m = im[b] ?? 0;
      out[b * frames + f] = Math.sqrt(r * r + m * m + p.epsilon);
    }
  }
  return out;
}

/** Number of frames `spectrogramTorch` produces for a sample count. */
export function spectrogramFrameCount(numSamples: number, p: SpectrogramParams): number {
  const padded = numSamples + (p.n_fft - p.hop_length);
  if (padded < p.n_fft) return 0;
  return Math.floor((padded - p.n_fft) / p.hop_length) + 1;
}
