/**
 * Golden test for the browser linear spectrogram against torch.
 *
 * The fixture is generated by contrib/voiceclone/export_onnx.py
 * (spectrogram_golden.json): a 100 ms deterministic voiced signal run through
 * the exact OpenVoice v2 `spectrogram_torch` frontend. The test skips when
 * the golden has not been generated locally (the file ships next to the ONNX
 * release assets, not in the repo).
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { linearSpectrogram, spectrogramFrameCount } from "./spectrogram";
import { MODEL_SAMPLE_RATE, type SpectrogramParams } from "./types";

// vitest rewrites import.meta.url to an http URL in the browser-like test
// environment, so resolve the golden via the runner cwd (ui/web) with a
// fallback for other roots.
const GOLDEN_CANDIDATES = [
  resolve(process.cwd(), "../../contrib/voiceclone/onnx/spectrogram_golden.json"),
  resolve(process.cwd(), "contrib/voiceclone/onnx/spectrogram_golden.json"),
];
const goldenPath = GOLDEN_CANDIDATES.find((p) => existsSync(p));

interface Golden {
  params: SpectrogramParams;
  signal: number[];
  spec: number[][];
}

const golden: Golden | null = goldenPath
  ? (JSON.parse(readFileSync(goldenPath, "utf-8")) as Golden)
  : null;

describe("linearSpectrogram vs torch golden", () => {
  it.skipIf(!golden)("matches spectrogram_torch sample-for-sample", () => {
    const { params, signal, spec } = golden!;
    const samples = new Float32Array(signal);
    const frames = spectrogramFrameCount(samples.length, params);
    const bins = params.n_fft / 2 + 1;

    expect(frames).toBe(spec[0]?.length);
    const out = linearSpectrogram(samples, params);
    expect(out).not.toBeNull();
    expect(out!.length).toBe(bins * frames);

    // Channel-major [freq][time] layout — compare element-wise with a tight
    // float32 tolerance (values are O(1e-2); 1e-4 abs covers fp32 noise while
    // still catching window/pad/layout mistakes, which produce O(1) errors).
    let maxDiff = 0;
    for (let f = 0; f < bins; f++) {
      const row = spec[f];
      if (!row) continue;
      for (let t = 0; t < frames && t < row.length; t++) {
        const got = out![f * frames + t] ?? 0;
        maxDiff = Math.max(maxDiff, Math.abs(got - (row[t] ?? 0)));
      }
    }
    expect(maxDiff).toBeLessThan(1e-4);
  });

  it("keeps the module defaults aligned with the OpenVoice v2 manifest", () => {
    expect(MODEL_SAMPLE_RATE).toBe(22050);
    if (!golden) return; // golden absent — contract asserted by export_onnx.py
    expect(golden.params.n_fft).toBe(1024);
    expect(golden.params.hop_length).toBe(256);
    expect(golden.params.win_length).toBe(1024);
    expect(golden.params.sample_rate).toBe(22050);
    expect(golden.params.epsilon).toBe(1e-6);
  });
});
